const word = ['jazz', 'apple', 'bed',
 'accent', 'berlin', 'cancel', 'caught', 
 'ability', 'able', 'about', 'above', 
 'acid', 'acne', 'adult', 'advice',
  'aerial', 'affair', 'again', 'ago', 
  'agent', 'alert', 'alias', 'alpha',
'amino', 'angel', 'anime', 'anxiety',
'any', 'approve', 'arcade', 'art', 'award',
'bang', 'bank', 'bat', 'bathroom', 'beach',
'beta', 'birth', 'boat', 'brave', 'button',
'cape', 'captain', 'catch', 'cat', 'charge',
'circle', 'clear', 'coin', 'comic', 'complex',
'context', 'cook', 'cow', 'cowboy', 'cowgirl',
'cubic', 'cycle', 'dance', 'deck', 'deny',
'design', 'dice', 'dig', 'diverse', 'done',
'dragon', 'dump', 'edge', 'elect', 'enemy',
'enhancment', 'equal', 'evil', 'exotic',
'eye', 'fail', 'favor', 'fiction', 'flag',
'flow', 'fly', 'fork', 'free', 'freeze', 
'fusion', 'gap', 'garden', 'gentle', 'girl',
'glass', 'golf', 'good', 'graphic', 'grown',
'halo', 'happy', 'hear', 'hero', 'hobby', 'hot',
'hypothetical', 'image', 'improve', 'innocent',
'invest', 'isle', 'jar', 'job', 'jungle', 'kingdom',
'ladder', 'late', 'leader', 'level', 'liable',
'lie', 'list', 'logic', 'luck', 'major',
'marble', 'mask', 'mechanical', 'member',
'metal', 'mile', 'mistake', 'mold', 'mouse',
'muscle', 'nail', 'necessary', 'new', 'noble',
'novel', 'object', 'off', 'old', 'operate',
'orbit', 'oven', 'panic', 'party', 'peer',
'pest', 'photo', 'pirate', 'plaza', 'polymer',
'post', 'pray', 'pretty', 'products', 'proper',
'put', 'railroad', 'reach', 'recipe', 'reel',
'relax', 'report', 'retail', 'ribbon', 'right',
'roll', 'rotary', 'rule', 'same','save',
'savage', 'science', 'season', 'sell',
'setup', 'shape', 'ship', 'sight', 'simple',
'sky', 'slide', 'social', 'solid', 'sound',
'speed', 'spouse', 'spy', 'stand', 'stick', 
'subject', 'suit', 'sure', 'survive', 'syntax',
'take', 'teach', 'tenant', 'thank', 'therapy',
'throw', 'tip', 'tired', 'tongue', 'tough',
'trail', 'trash', 'triple', 'type', 'undo',
'unusual', 'use', 'value', 'vampire',
'village', 'wagon', 'watch', 'well', 'wire',
'worst', 'yard', 'yeild', 'yoga', 'zone',
'zoo'];